image: ubuntu/latest
secrets:
  - 22254790-6b01-431a-953e-323215895daa
tasks:
  - test: |
      pip install circuitpython-build-tools Sphinx sphinx-rtd-theme tox codecov
      tox
      # - circuitpython-build-bundles --filename_prefix circuitroomba --library_location .
      export CODECOV=$(cat ~/.codecov)
      codecov -t $CODECOV
  # - pypi: |
  #     pip install -U twine
  #     python setup.py sdist
  #     twine upload dist/*
