image: python:3.7

test:
  stage: test
  script:
    - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme tox codecov
    - tox
    # - circuitpython-build-bundles --filename_prefix circuitroomba --library_location .
    - codecov -t $CODECOV_TOKEN
  artifacts:
    paths:
      - htmlcov/

pypi:
  stage: deploy
  cache: {}
  script:
    - pip install -U twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags
    - master

