image: python:3.7

test:
  stage: test
  script:
    - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme tox codecov
    - tox
    # - circuitpython-build-bundles --filename_prefix circuitroomba --library_location .
    - codecov --token="fd0aace5-ac25-4b4d-8004-4304adc0c6f2"
  artifacts:
    paths:
      - htmlcov/

