stages:
  - test

test:
  stage: test
  script:
    - pip install tox
    - tox
    - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
    - circuitpython-build-bundles --filename_prefix circuitroomba --library_location .
    - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
